"""Problem Details (RFC 7807) error response schemas."""


from pydantic import BaseModel, ConfigDict, Field, field_validator


class ProblemDetails(BaseModel):
    """Problem Details for HTTP APIs (RFC 7807).

    This model represents a standard error response format that provides
    machine-readable and human-readable error information without exposing
    sensitive service implementation details.

    Attributes:
        type: A URI reference that identifies the problem type.
        title: A short, human-readable summary of the problem type.
        status: The HTTP status code generated by the origin server.
        detail: A human-readable explanation specific to this occurrence.
        instance: A URI reference that identifies the specific occurrence.
    """

    type: str = Field(
        ...,
        description="A URI reference that identifies the problem type",
        examples=["https://api.dilcore.ai/problems/validation-error"],
    )
    title: str = Field(
        ...,
        description="A short, human-readable summary of the problem type",
        examples=["Validation Error"],
    )
    status: int = Field(
        ...,
        ge=400,
        le=599,
        description="The HTTP status code",
        examples=[400],
    )
    detail: str = Field(
        ...,
        description="A human-readable explanation specific to this occurrence",
        examples=["The request body contains invalid data"],
    )
    instance: str = Field(
        ...,
        description="A URI reference that identifies the specific occurrence",
        examples=["/api/v1/metadata/generate"],
    )

    @field_validator("status")
    @classmethod
    def validate_status(cls, v: int) -> int:
        """Validate that status is an error status code (4xx or 5xx)."""
        if v < 400 or v > 599:
            raise ValueError("Status must be an error status code (400-599)")
        return v

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "type": "https://api.dilcore.ai/problems/validation-error",
                "title": "Validation Error",
                "status": 400,
                "detail": "The prompt field must be between 1 and 4000 characters",
                "instance": "/api/v1/metadata/generate",
            }
        }
    )
