"""Supervisor node for the Blueprints agent."""

import logging
from typing import Literal

from langchain_core.messages import SystemMessage
from langgraph.types import Command
from pydantic import BaseModel, Field

from agents.blueprints.prompts import SUPERVISOR_SYSTEM_PROMPT
from agents.blueprints.state import BlueprintsState
from shared.models import LLMDecision

logger = logging.getLogger(__name__)

# Route Constants
ASK_ROUTE = "ask"
IDENTIFY_INTENT_ROUTE = "identify_intent"
GENERATE_ROUTE = "generate"

# Type definition for route decisions
RouteNames = Literal["ask", "identify_intent", "generate"]


class SupervisorDecision(BaseModel):
    """The decision model generated by the supervisor to route the user."""

    next_route: RouteNames = Field(
        ...,
        description="The name of the next node to route the user to based on their intent.",
    )


class SupervisorNode:
    """Supervisor node that uses structured output to decide the next route."""

    def __init__(self, llm):
        """Initialize the node with the LLM instance."""
        self._llm = llm
        self._structured_llm = llm.with_structured_output(LLMDecision[SupervisorDecision])

    async def __call__(self, state: BlueprintsState) -> Command[RouteNames]:
        """Evaluate user messages and return the next route."""
        messages = [SystemMessage(content=SUPERVISOR_SYSTEM_PROMPT)] + state["messages"]

        try:
            output: LLMDecision[SupervisorDecision] = await self._structured_llm.ainvoke(messages)
            decision = output.decision
            route = getattr(decision, "next_route", IDENTIFY_INTENT_ROUTE)
            reasoning = output.reasoning
        except Exception as e:
            logger.error(f"Failed to parse supervisor decision: {e}. Falling back to {IDENTIFY_INTENT_ROUTE}.")
            route = IDENTIFY_INTENT_ROUTE
            reasoning = "Failed to parse model output or recognize intent."

        if route not in [ASK_ROUTE, IDENTIFY_INTENT_ROUTE, GENERATE_ROUTE]:
            logger.warning(f"Unexpected route from LLM: {route}. Falling back to {IDENTIFY_INTENT_ROUTE}.")
            route = IDENTIFY_INTENT_ROUTE

        logger.info(f"Supervisor reasoning: {reasoning}")
        logger.info(f"Supervisor routed to: {route}")

        return Command(goto=route)
