"""Supervisor node for the Blueprints agent."""

import logging
from typing import Literal

from langchain_core.messages import SystemMessage
from pydantic import BaseModel, Field

from agents.blueprints.prompts import SUPERVISOR_SYSTEM_PROMPT
from agents.blueprints.state import BlueprintsState

logger = logging.getLogger(__name__)

# Route Constants
ASK_ROUTE = "ask"
IDENTIFY_INTENT_ROUTE = "identify_intent"
GENERATE_ROUTE = "generate"

# Type definition for route decisions
RouteNames = Literal["ask", "identify_intent", "generate"]


class SupervisorDecision(BaseModel):
    """The decision model generated by the supervisor to route the user."""

    next_route: RouteNames = Field(
        ...,
        description="The name of the next node to route the user to based on their intent.",
    )


class SupervisorNode:
    """Supervisor node that uses structured output to decide the next route."""

    def __init__(self, llm):
        """Initialize the node with the LLM instance."""
        self._llm = llm

    async def __call__(self, state: BlueprintsState) -> dict:
        """Evaluate user messages and return the next route."""
        messages = [SystemMessage(content=SUPERVISOR_SYSTEM_PROMPT)] + state["messages"]
        structured_llm = self._llm.with_structured_output(SupervisorDecision)
        decision: SupervisorDecision = await structured_llm.ainvoke(messages)

        logger.info(f"Supervisor routed to: {decision.next_route}")

        return {"next_route": decision.next_route}
