"""Supervisor node for the Blueprints agent."""

import logging

from langchain_core.messages import SystemMessage
from langgraph.types import Command
from pydantic import BaseModel, Field

from agents.blueprints.constants import (
    ALL_ROUTES,
    IDENTIFY_INTENT_ROUTE,
    RouteNames,
)
from agents.blueprints.prompts import SUPERVISOR_SYSTEM_PROMPT
from agents.blueprints.state import BlueprintsState
from shared.models import LLMDecision

logger = logging.getLogger(__name__)


class SupervisorDecision(BaseModel):
    """The decision model generated by the supervisor to route the user."""

    next_route: RouteNames = Field(
        ...,
        description="The name of the next node to route the user to based on their intent.",
    )


class SupervisorNode:
    """Phase-aware supervisor that routes to the correct sub-agent."""

    def __init__(self, llm):
        self._llm = llm
        self._structured_llm = llm.with_structured_output(LLMDecision[SupervisorDecision])

    async def __call__(self, state: BlueprintsState) -> Command[RouteNames]:
        current_phase = state.get("current_phase", "")
        design_context = state.get("design_context", [])
        generation_plan = state.get("generation_plan", [])
        plan_confirmed = state.get("generation_plan_confirmed", False)

        prompt = SUPERVISOR_SYSTEM_PROMPT.format(
            current_phase=current_phase,
            has_design_context=bool(design_context),
            has_pending_plan=bool(generation_plan and not plan_confirmed),
        )

        messages = [SystemMessage(content=prompt)] + state["messages"]

        try:
            output: LLMDecision[SupervisorDecision] = await self._structured_llm.ainvoke(messages)
            route = output.decision.next_route
            reasoning = output.reasoning
        except Exception:
            logger.exception("Failed to parse supervisor decision. Falling back to %s.", IDENTIFY_INTENT_ROUTE)
            route = IDENTIFY_INTENT_ROUTE
            reasoning = "Failed to parse model output or recognize intent."

        if route not in ALL_ROUTES:
            logger.warning("Unexpected route from LLM: %s. Falling back to %s.", route, IDENTIFY_INTENT_ROUTE)
            route = IDENTIFY_INTENT_ROUTE

        logger.debug("Supervisor reasoning: %s", reasoning)
        logger.info("Supervisor routed to: %s", route)

        return Command(goto=route, update={"current_phase": route})
